### ISSUE TITLE
Missing the actual code

### ISSUE THREAD

**Issue by antonkandersson** [AdamBrodzinski/meteor-react-test-helpers#1]
Hi, great tutorial on Medium. 
Just came here looking for the test helpers, seem to have missed it when pushing? Only README and LICENSE available. 

Have a great one,
Anton

**Comment by AdamBrodzinski** [comment]
Ah thanks for the heads up! To be honest I forgot about this because I switched to using webpack and ES6 modules in Meteor. The stuff that was supposed to get put in there was basically these:

https://github.com/AdamBrodzinski/react-meteor-tests/blob/master/tests/jasmine/client/unit/components/EvenOdd_spec.js#L8-L14

https://github.com/AdamBrodzinski/react-meteor-tests/blob/master/tests/jasmine/client/unit/spec_helper.js

**Comment by antonkandersson** [comment]
Ok :) I'll close then.
